queue_rules:
- name: default
  conditions:
  - status-success=all tests passed
pull_request_rules:
- name: automatic squash-and-merge on CI success and review
  conditions:
  - status-success=all tests passed
  - '#approved-reviews-by>=1'
  - '#changes-requested-reviews-by=0'
  - base=master
  - label="Please Merge"
  - label!="DO NOT MERGE"
  - label!="bp-conflict"
  actions:
    queue:
      name: default
      method: squash
      update_method: merge
- name: backport to 0.3.x
  conditions:
  - merged
  - base=master
  - milestone=0.3.x
  actions:
    backport:
      branches:
      - 0.3.x
      ignore_conflicts: true
      label_conflicts: bp-conflict
    label:
      add:
      - Backported
- name: label Mergify backport PR
  conditions:
  - body~=This is an automated backport of pull request \#\d+ done by Mergify
  actions:
    label:
      add:
      - Backport
- name: automatic squash-and-mege of 0.3.x backport PRs
  conditions:
  - status-success=all tests passed
  - '#changes-requested-reviews-by=0'
  - base=0.3.x
  - label="Backport"
  - label!="DO NOT MERGE"
  - label!="bp-conflict"
  actions:
    queue:
      name: default
      method: squash
      update_method: merge
