/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chiseltest_simulator_jni_JniAPI_00024 */

#ifndef _Included_chiseltest_simulator_jni_JniAPI_00024
#define _Included_chiseltest_simulator_jni_JniAPI_00024
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      chiseltest_simulator_jni_JniAPI_00024
 * Method:     load_1so
 * Signature:  (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_chiseltest_simulator_jni_JniAPI_00024_load_1so
  (JNIEnv *, jobject, jstring);

/*
 * Class:      chiseltest_simulator_jni_JniAPI_00024
 * Method:     call_1sim_1init
 * Signature:  (I)J
 */
JNIEXPORT jlong JNICALL Java_chiseltest_simulator_jni_JniAPI_00024_call_1sim_1init
  (JNIEnv *, jobject, jint);

/*
 * Class:      chiseltest_simulator_jni_JniAPI_00024
 * Method:     call_1step
 * Signature:  (IJI)I
 */
JNIEXPORT jlong JNICALL Java_chiseltest_simulator_jni_JniAPI_00024_call_1step
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:      chiseltest_simulator_jni_JniAPI_00024
 * Method:     call_1update
 * Signature:  (IJ)V
 */
JNIEXPORT void JNICALL Java_chiseltest_simulator_jni_JniAPI_00024_call_1update
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:      chiseltest_simulator_jni_JniAPI_00024
 * Method:     call_1finish
 * Signature:  (IJ)V
 */
JNIEXPORT void JNICALL Java_chiseltest_simulator_jni_JniAPI_00024_call_1finish
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:      chiseltest_simulator_jni_JniAPI_00024
 * Method:     call_1resetCoverage
 * Signature:  (IJ)V
 */
JNIEXPORT void JNICALL Java_chiseltest_simulator_jni_JniAPI_00024_call_1resetCoverage
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:      chiseltest_simulator_jni_JniAPI_00024
 * Method:     call_1writeCoverage
 * Signature:  (IJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_chiseltest_simulator_jni_JniAPI_00024_call_1writeCoverage
  (JNIEnv *, jobject, jint, jlong, jstring);

/*
 * Class:      chiseltest_simulator_jni_JniAPI_00024
 * Method:     call_1poke
 * Signature:  (IJII)I
 */
JNIEXPORT void JNICALL Java_chiseltest_simulator_jni_JniAPI_00024_call_1poke
  (JNIEnv *, jobject, jint, jlong, jint, jlong);

/*
 * Class:      chiseltest_simulator_jni_JniAPI_00024
 * Method:     call_1peek
 * Signature:  (IJI)I
 */
JNIEXPORT jlong JNICALL Java_chiseltest_simulator_jni_JniAPI_00024_call_1peek
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:      chiseltest_simulator_jni_JniAPI_00024
 * Method:     call_1poke_1wide
 * Signature:  (IJIII)V
 */
JNIEXPORT void JNICALL Java_chiseltest_simulator_jni_JniAPI_00024_call_1poke_1wide
  (JNIEnv *, jobject, jint, jlong, jint, jint, jlong);

/*
 * Class:      chiseltest_simulator_jni_JniAPI_00024
 * Method:     call_1peek_1wide
 * Signature:  (IJII)I
 */
JNIEXPORT jlong JNICALL Java_chiseltest_simulator_jni_JniAPI_00024_call_1peek_1wide
  (JNIEnv *, jobject, jint, jlong, jint, jint);

/*
 * Class:      chiseltest_simulator_jni_JniAPI_00024
 * Method:     call_1set_1args
 * Signature:  (IJILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_chiseltest_simulator_jni_JniAPI_00024_call_1set_1args
  (JNIEnv *, jobject, jint, jlong, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
